[package]
name = "circulate"
version = "0.0.0"
description = "Circular buffer for byte oriented I/O."
license = "MIT"
edition = "2021"
repository = "https://github.com/AidoP/circulate/"

[features]
default = []
no_std = []

[dependencies]
